services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pinkeen\ApiDebugBundle\:
        resource: '../../*'
        exclude: '../../{Resources,Twig}'

    Pinkeen\ApiDebugBundle\DataCollector\Data\AbstractCallData:
        alias: Pinkeen\ApiDebugBundle\DataCollector\Data\PsrCallData

    Pinkeen\ApiDebugBundle\DataCollector\ApiConsumerDataCollector:
        tags:
            - { name: data_collector, template: "PinkeenApiDebugBundle:Collector:api_consumer.html.twig", id: "api_consumer" }
            - { name: kernel.event_listener, event: api_call, method: collectCall }

    Pinkeen\ApiDebugBundle\Bridge\Guzzle\Middleware\DataCollectorMiddleware: ~
    Pinkeen\ApiDebugBundle\Bridge\Guzzle\Service\GuzzleClientFactory:
        arguments:
            $debug: '%kernel.debug%'
        public: true

    Pinkeen\ApiDebugBundle\Bridge\RingPHP\Middleware\DataCollectorMiddleware: ~
    Pinkeen\ApiDebugBundle\Bridge\RingPHP\Service\RingPHPHandlerFactory:
        arguments:
            $debug: '%kernel.debug%'
        public: true
